language: node_js
services:
- docker
env:
  global:
  - DOCKER_IMAGE_NAME="backend-feed"
  - DOCKER_USERNAME="lindtdev"
  - secure: c0qN+SbIa6FfbRzGgcngE8xDrY4AlXeRakHNz7iUAroCJYqnoKyP27Qqg7yX/Fr9I5WNTnb6roEHTlNQgn2i9IOkwjPKgn8EybL60Y15QUUjLAyFFfRaOM2ubhdHwEDaE4ZNEjkGI9BzeWNvCxXVDxu99uhUypfMXTSDNNF70KTJjqKX2xuoSm9KAiP2kbMa9c5YV+JUZ8zgn6/0ZgTJpz5GghQyEInHRUgTRGUQtdyJPVuKdTy8KssVLhN3GKgkGMcruG4lN7clVdF1n/iPgBJHlxAXq0pRJAHKn2KnAP/YA4LJRkWjbV2LBV9ICMJnJDs7a6OyT7RU/MaGMIV8jUgt6QoJwQq89DDSQO+uLftY2czD1ocjD01cORbyDu1Uyxv7D1hA9IgRg9DtEEPO6heXRjxFlreJzmuPq8we56XFsUrNCgq2t8nkGEzd32BPlUX/H38Eh9Z/k+FgVPTtDKx2ljHZTiYbCNiiZW4sQhD9cqIrhlSNCDw009wL8dZPGl2/BAftzT7F28k92iwD4aZuZYr7X7lPw2sYP2m7qEapc7GdrmMrBUJ9uSW3/KZTYhrusr/goQCd/hOz9aMA6ckits6dm7SeMu7LDvblCPUVfND0KkJFKxd/3W3CuJIZOnyrGLu6l8fMMWT5SKs4sNeT4Mu1pDTX7Lf52BsNg10=
before_install:
- docker -v
install: true
script:
- docker build -t $DOCKER_IMAGE_NAME .
- docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
deploy:
  provider: script
  script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    && docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
  on:
    branch: ci
