language: node_js
services:
- docker
env:
  global:
  - DOCKER_IMAGE_NAME=backend-feed
  - DOCKER_USERNAME=lindtdev
  - secure: Q7s+xO6pYX/kWnldPS2louhe0K/foh6hLluXGI140BP7nACBJ8BnEkOdMJjNKSQLMoW7l/381t1SG0syrS76qO9wyO98Prbo/Z8GSeD6QKbABb0Y8m0kvBCatk/U5/JOJlgSRVt5mt9PRtcphvJHQrL5eqbQJgSRSqq65rOh8MSCG/nEscVMB2YYkuTAgzCYuuDVnLrsdSrvgc+WWyaqt4bKSEfpIWTdlZ7VKBp0bDyWj4159mITLmZtsW1roKIrjSmLFm1tqVmLwTYmYFXbrXiIo5nebr/tO2LKPRYYWj+byrWcGQCysv7oL7SXTmVYYuPwA44LP0k2R3wQZP2ZngleRuGfeGeTBlH2/FT9u4+cRQ/R1kM3sy0CkdSRupLYOfj3ZjE6bonMNWH7pHBfY9nKSyjWIZCyA4I17WklTt2oWrQZ+UfxnwMCratWtDS1bXpp0QsEkGx5DdkT7VgmS2u7lqgjAGsEgcsk0mHZa5nhG0YekCn28yOzcCAySY3k/OngxWfj/J0juyEUJ4+gF/ykh4NiqjkgYn1EN/0JIPjJc3pvF4jv1DTxnIMjFBBI63GnhD05iZktFi+YYf1Ywpe0IOSxEQaG0OX3OOr/n+Gf14MVOXZQejh6/e4lDBUlK/bqM5JR9XqofdmCGpoRsqdYt6uDcCj223lxhRc3HUQ=
  - secure: dB/uOOBryNo9TXb/ycmmj4QiX9acYv/lTjV1iunVexkw7iu/uhEba+wpsvMXKQ42cRMHI6riGnlrh+dZnY2FUGapNbGbXwpj0taeMVk2ZMiO50mu5vF2urhPb+zI29DS0BjZHtzTCX5kmV/WF8tJ4JhC/bM/XUamGvBucHAWUptU3eqq502RuwOJ50NDbPe+BXhf7RX3uq/Bj40Ce4fqtgduEzLd6bqPh3CrWtaKMf8hQipwmVy3OD6D07MnCc2e1Hdj32pCyvlcgfoh1nl7+wBpuNnmITYTdSLw/dhFhh8vuTUqlt44CjFZv2g+vi5bHdwHXcKL3emjyNGOUOo/K0XLLy31H9IksDwaeiXmXATihMqa1Aev5ZhRGg8Lem64awKcv1qOyHyYnSnU7rJkUcQna4zhy2mdXgurKIAHb5rJKZuHLK3Gzyn/gnVoj7euv5oUpJu4dQDumr7OTDsp4iBaHYwUcO1XzBNcwXoAH6kqTkSrvS74VOkswjZzHZOplTy4aKYBgDcMIEx0QCdJxGnPVqi9StsgvYoNWad29VZPCDAmK5dPnccXw/E9dh2ZCyBX+ijzsr0HHWVtjDmIE1iFdd5JyHMJFkG11GIffgQkir12IJwRsHjlnBLvxncd48Dr47Rrl2wGkehZ/5mbeN0fjWIN+QuGPn/dTLrprfs=
before_install:
- docker -v
install: true
script:
- docker build -t $DOCKER_IMAGE_NAME .
- docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
deploy:
  provider: script
  script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    && docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
  on:
    branch: ci
