language: node_js
services:
- docker
env:
  global:
  - DOCKER_IMAGE_NAME=backend-feed
  - DOCKER_USERNAME=lindtdev
  - secure: kW1x/ERB0CUjdo8cvuPlMO5i298WZnL+dmnJK28zA79s59kpy8LoXLVXQHYol2OYRWgLEcYfHHUTOuSVRVuh8FC/xrzhJFm3ha/xbxxUVO9kR+9juUrX9f39WR3pN02oifG3bOn+QIg8J/OIa0pQhji0uWSj0+L8I/5k+d/2qrjnMGj6ni0d2nVizmEo9V2JgWfE9qlTuy0c6e8Lkm5KolgJA6wOPYj+8L8qno4T0NhUzqCkS+Lf33NDJGSRIGghoFRtepdVBpTbggiPg8SGXLPkk+F2U+FVUcJccPW+Cl+/qlWR74USj55+Cv/mt1+pDa7XUq/a76ejdWZSOl2UJOkBcf5TXzMhZNJEhC4JWQFZwVpm6h+nyHV1xPJNzfZ4q+xskXjgTj1MI1cD0mAyoeKAs4yY6KZOFOs9h5bMxl46ivWkrOb3fzdBpha0nM+Ljb5D3bW/pvtXJEL+B8BkT73gLzqKgCyl7BZHb6sZs0x7ZexDTnrp0GnoTSvoxCTQAxzPxFMPHUjkcm1iENFsjo7TYofSDs6FjIm37mNZ2iVt8iX0lWfGuxG6OKyd2hnPbxF80aKX3PusgL3kzBaTJjIz0+hXlqUyYN840emWFb1JUpKQH8zM6CHrwJngE702KP3Ofq/QAgV1vd/6bGMeuOo7MyRP8cjw1kNh+UVpWJY=
before_install:
- docker -v
install: true
script:
- docker build -t $DOCKER_IMAGE_NAME .
- docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
deploy:
  provider: script
  script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    && docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
  on:
    branch: ci
