language: node_js
services:
- docker
env:
  global:
  - DOCKER_IMAGE_NAME=backend-feed
  -  DOCKER_USERNAME=lindtdev
  - secure: D6dYX0EXWEjHSJvzLpQm+ksAo0UE4eal09Xd+R8om2UO7EgoLxXKxyjJHD+k6cyd0CciCBeDNj+1gg7cuwjN2AFzV9rravLJY29L3Fntezt15MT0HnXcD8wBKNvYIo3st4M3fraQir65xE2xb5wEwNpMkQmOLKF0J5JEd8DmF9PPErbI4RfxhtRkZNhnZefUonXcW1WnAIqdaGVCV08Y0jy7Bno+zc38VBuxUSqGyNfltA05RRhNdyi6/wVdkw6DdePxXzmRCEjxU0McKtoxwfLItRSJiPEdEMgUwLd65TNQg9GdAu8psHfOOPBY3Q+XNqj1c4xXFrykl9vNeDzns87GMTjWLfh9N+uar/gBiP5s3Tn5qYortFXybpM7dt29sFSG2xWupXHJ4MJJbqmgm7eQ3IOa21UXysFztfR1A57MDIPgWwYTQO5WBeXqTxwZNGYIcRyI1QKVCg5DbmrOxQ7siD+bsIIjPXNAi1z6b6ySQJhz4R3BHv9PgnaSTlE+Fydn4OrrNZF613PpjMNWlh0KVhXvk8gVvhCN61RDF6pL+2xms/0HVR93emn/TBSC2KHEj8fBLk3lmtrZ4TBafWb9KMTY/MgwlHwgXAd2xXMrIPgxVNbrpz0YULIsIiRLp4/L4mJEWpjtK0kCpDDAwxObAnrVjGhJHu2ostfaZ5k=
install: true
script:
- docker build -t $DOCKER_IMAGE_NAME .
- docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
after_success:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
