language: node_js


services: 
- docker


env:
  global:
  - DOCKER_IMAGE_NAME="backend-feed"
  - DOCKER_USERNAME="KGdwt3z29v3QS3f2ZFmKe4Ukv2iIoyoj4bQTQQLnA3QLgZ27cZ8iZOWPNi0AEVamBz6Yk1O1tB6yvfa634UFQZV1URfWIg4Smmxt0wCrLxNtKravOD+6Hx+Zj/PpYLVlXGFIoQ0hdbYsSwnZ7OPF+Psu6Yob7s1mYHCzZnHcTbhJjgldiHrS+Bhp19j38lrkfaWfjfH/KGVJDNqtZH0kmHdkjjuPb9hRgYrAXMgddY3QyIPRKPC9lFp678mLgfKhkyD5Qv2Y9mo5oPTaGe2sRIkBf7qo9drmLtxRKHZ2X/qemlLK2jZnoOaFHtYM4sRauKq1F3Tualh0gKHa/jyhDwQJovwXrG3MeznIH2274c0oMnueYeSI6DSQk1slk6T6EkEPehKZOChnqu6vOzWfdLjUigHdtbr0109JPvvzb4oZGNGQUD/xl424f6qkudQ8xLS10Vo6uzfu23M014wAEPA/X5OpibJA31TwVpa2+dH5/ICpVkoDTc+HApeRQGRuK5YZyCzRJqKk9QlSl1UOfcOm3T/JqV23Y2MO1+4e6zCfTCcTPM1bhVvN1m4OcOcbiPJwJuojXmxFbFtE0N8GCVrPcBfdc2AE2XM7txsmLFny6E7S7coFnBHVX7RldBL5mHxe0AFRrR6KUtDxvZtSZyjd3e8BlS8yjrCqgDgzBm8="
  - DOCKER_PASSWORD="mSg7bAszMaWWMRDZr1SmBP9LwZBRNpjs8cKZRLgS7drYf2+2bRsI429KzzNiGDoqDk2nFajjQgX0VyJV4hq4oZl3uzEZWKK4hfRYRMwpgzYXiMHn1AIA1TitlvwiO/Fb0Ux9NoYD/dyQh5Lq5yarWMlrvmUktll67j6NpUnuo34wRk3fRkAHWDL+9/J0Rk9T0C1ZFaKdMs8oYi1dTzIGO8cm9Hu9hIerJHb5Ft5KPUQWU0SRSpetbtoMFKXrDz4cj4lwpbLV7xxBnMrQow8I2kdWYtx+zv8oC4JE2M3mVAGRD/ytvxUSrCXsRh0n86qdHHutdqvEfeYcmSCcECpDw1cNkEYnL5dxrTTxmKUWu8VcHKjf0KjlPpKwqQzaylEhBMg2sIJbh/9X0K2opOgmq8ay0RzDzdUBZ3/DNE+s1m/Xc9u5lZ6iCwz+FGVnF6ZbMPSaEAmvYkh+Y1ONor7JbslcxBQjzW0kMJIfSGCTk3DxD/S/6MbmDze9/JnkX9b9bfvNZdPMunH+7b2eidnukxrKDtMcbkx5kLEj+105MKewL2/vdYvEbEs5vPYUsNcJ87LpMmXTrNr1qrtkH03lwOxsr7xy3g72fY0nTeWWHf1xriZIDCh5SASoPmJ2Ck5Mm0FdwycBj8L83SjQPqUjNtirrZ2NJsQepSQB/6fanGY="
#these are going to be replaced by env variables later but for now probably easier to test like this


before_install:
  - docker -v


install: true


script:
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
  # add version number??


deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
  on:
    branch: ci
