language: node_js
services:
- docker
env:
- secure: fnQbog19ZegP0fx+JvPJPZhN6opF8Uek3sEnXQA7arB7TfN+z70iXUgWnFuGhXFuaDiJp5jvTG5L79tqq3Gos4OVpSRU02SOCebCf7FBSyBnSG4F7Y5hNbhBaOHu7jxyTZbs9i1SoXL4EZDCyIK/NtsL0DYNiHQhsJOlc2fKM19e2NZW5DCA2dR6LjGsgWBmG1oS+YM5FATf0CGafQfrGmYCv/Yesx80zSUXZijsUxvAWjmMPZSsk8TSY0uVEokBN+CB9Okf0owFRyiX7DbWkRfFuxausO6Fwcek/095HMhQh1pxIx7IJR3sKDM+1U+OCLBl+vl+5tAzb0Vuw79tR7t93sNxPdhfWnE2po3QO2ZxXu2cWYJi1+ZgquBiSlgtEziqnX7RTdmdTq8agwwKmwIj203tIjpsEofhi6FyNhwSBKWe+/vzhAjTGUzTihZZYeW+yXnn0zsSlm2DLbyDmWacYWv7SAo9iJ0mnh+1tIvSAl6eOMrn3iDxG8Bz3NsZAmCllBaSGy9tlXhqsNUWFxxnt+Wcfi2zqqbLvxUAb86LYhSW0lle+R8gOS0ebXOLtUqSYbXY3U/NZTNx28cwN9sbpeZu2s6jItKx6hBrVHNYPc10VjsV8TfM5icr48PRUlb4qz/bZJYlk6zbm5d2vZ/xWGh/7IRelFG4ltW3bnE=
before_install:
- docker -v
install: true
script:
#- docker build -t $DOCKER_IMAGE_NAME .
#- docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
- docker build -t backend-feed .
- docker tag backend-feed lindtdev/backend-feed
deploy:
  provider: script
  script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
   && docker push lindtdev/backend-feed
   # && docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
  on:
    branch: ci
