language: node_js
services:
- docker
env:
  global:
  - DOCKER_IMAGE_NAME=backend-feed
  - DOCKER_USERNAME=___INSERT_YOUR_DOCKER_USERNAME___
  # TO PASS YOUR DOCKER PASSWORD SECURELY, PASS IT VIA THE COMMAND LINE
  # THE COMMAND IS "travis encrypt DOCKER_PASSWORD=YOUR_DOCKER_PASSWORD --add"
  # AFTER THAT YOU SHOULD SEE A NEW ENTRY IN env: global: SAYING secure: __hash__ 
install: true
script:
- docker build -t $DOCKER_IMAGE_NAME .
- docker tag  $DOCKER_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
after_success:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
